### PR TITLE
user rights are now returned as a list, not a hashmap

### PR DESCRIPTION
**Pull request by nmonterroso**
@Wikia/services-team @jcellary @macbre 
User rights are now returned as a list, not a hashmap. This change was causing an issue in the user-permissions service where permissions could not be deserialized properly, so all requests were resulting in a `500` response. This happened with the release on Oct 29, 2015 because of [this commit](https://github.com/Wikia/app/commit/3a3a760257752b63cba93d5a6ad4862679db1cdc#diff-62fd5cdf832836f47c56a36a957cc37aR156)

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'java.util.Map'.](https://github.com/Wikia/pandora/blob/81318e6ba6014933be527a0fe762637fb9497539/lib/mediawiki-fluent-api/src/main/java/com/wikia/mwapi/domain/User.java#L6) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by ArturKlajnerok** [comment]
Ltgm :+1:

**Comment by macbre** [comment]
@nmonterroso, thanks!

**Comment by jcellary** [comment]
Yeah, thanks for taking things in your own hands :)

**Pull request merged**
