### PR TITLE
Pandora Rename: Initial reorganization

### PR DESCRIPTION
**Pull request by pchojnacki**
My proposal for organizing subfolders and renaming of the subprojects.
after that renaming of the packages should follow
/cc @cmiller-wikia @drsnyder @nmonterroso @sqreek 

```
Root project 'pandora'
+--- Project ':lib'
|    +--- Project ':lib:consul-config'
|    +--- Project ':lib:facade-gateway'
|    +--- Project ':lib:mediawiki-fluent-api'
|    +--- Project ':lib:mercury-api'
|    +--- Project ':lib:nirvana-api'
|    \--- Project ':lib:service-core'
\--- Project ':service'
     +--- Project ':service:example'
     +--- Project ':service:facade'
     \--- Project ':service:mobile-config
```

### CODE REVIEW

**Comment by pchojnacki** [comment]
FWIW integration tests are failing because we still are mocking the config through jenkins.

**Comment by nmonterroso** [comment]
I really like the separation of `lib` and `service`. Can we rename `:service:facade` to something more specific (like `mercury-facade` or `mediawiki-facade`), since we might create a different facade service at some point in the future?

**Comment by sqreek** [comment]
IMO we can also renamce mercury-api to mercury-api-replacement, move it to service,and then remove it from gradle.
Why?
I was worked at it on early stage of pandora when there was 2 aproach to make it.
1) Just get response from mercury and wrap it with hall
2) Where it was possible, use mediawiki api for collect data.

so ...
1) For now there is no request for continue develop this service, we can back to it when we need to.
2) It's getting resources from other library (core, now facade) using code, not service request, so it's not valid with our approach.

**Comment by sqreek** [comment]
I moved, renamed, and disable from gradle mercury-api
/cc @cmiller-wikia @drsnyder @nmonterroso @pchojnacki 

```
Root project 'pandora'
+--- Project ':lib'
|    +--- Project ':lib:consul-config'
|    +--- Project ':lib:facade-gateway'
|    +--- Project ':lib:mediawiki-fluent-api'
|    +--- Project ':lib:nirvana-api'
|    \--- Project ':lib:service-core'
\--- Project ':service'
     +--- Project ':service:example'
     +--- Project ':service:facade'
     \--- Project ':service:mobile-config
```

**Comment by pchojnacki** [comment]
lets not keep this hanging too long since this actually blocks other work.
so I obviously vote Yes. 
@nmonterroso ?

**Comment by nmonterroso** [comment]
Sure LGTM

**Pull request merged**
