### PR TITLE
SOC-1519 Add Mediawiki 119 tenant in Discussions

### PR DESCRIPTION
**Pull request by armonr**
/CC @garthwebb @jimmordino 

https://wikia-inc.atlassian.net/browse/SOC-1519

### CODE REVIEW

**Comment by jimmordino** [comment]
:+1:  Jenkins tests are timing out

**Comment by bkoval** [comment]
@jimmordino You can always rebuild the Jenkins job from the left menu on a job details page :)

**Comment by jimmordino** [comment]
That was the first thing I did, but it timed out again.

**Comment by bkoval** [comment]
Ah, ok, yeah, I've run it again and it's on it's way to a timeout again ;/

**Comment by jimmordino** [comment]
Jenkins is essential, but not to this pull request as it's just a SQL script.  We need to get tests working again, but that shouldn't hold up this particular merge.

**Comment by armonr** [comment]
Thanks, I'll be merging this then.

**Pull request merged**
