### PR TITLE
DAT-3411 more robust scrollbox detection

### PR DESCRIPTION
**Pull request by SebastianMarzjan**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues:
* MAJOR 3 major
* MINOR 4 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unnecessary import: java.lang classes are always implicitly imported.](https://github.com/Wikia/pandora/blob/3c289cff567936504deb421876ff934a014d3ae3/workers/template-classification-worker/src/main/java/com/wikia/workers/templateclassificationworker/matchers/ScrollboxMatcher.java#L7) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* MINOR [Define a constant instead of duplicating this literal "other" 3 times.](https://github.com/Wikia/pandora/blob/3c289cff567936504deb421876ff934a014d3ae3/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L37) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/pandora/blob/3c289cff567936504deb421876ff934a014d3ae3/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L111) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)
* MINOR [Define a constant instead of duplicating this literal "quote" 3 times.](https://github.com/Wikia/pandora/blob/3c289cff567936504deb421876ff934a014d3ae3/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L65) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "navbox" 3 times.](https://github.com/Wikia/pandora/blob/3c289cff567936504deb421876ff934a014d3ae3/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L51) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Define and throw a dedicated exception instead of using a generic one.](https://github.com/Wikia/pandora/blob/3c289cff567936504deb421876ff934a014d3ae3/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L24) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00112)
* MAJOR [Either remove or fill this block of code.](https://github.com/Wikia/pandora/blob/3c289cff567936504deb421876ff934a014d3ae3/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L111) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00108)

**Comment by idradm** [comment]
LGTM except sonar comment about override import

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues:
* MAJOR 3 major
* MINOR 4 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Either remove or fill this block of code.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L118) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00108)
* MINOR [Define a constant instead of duplicating this literal "navbox" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L51) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "other" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L37) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Define and throw a dedicated exception instead of using a generic one.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L24) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00112)
* MINOR [Define a constant instead of duplicating this literal "quote" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L65) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L118) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)
* MINOR [Define a constant instead of duplicating this literal "scrollbox" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L86) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)

**Comment by idradm** [comment]
LGTM, but please be aware of formatting changes on merging with main branch

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues:
* MAJOR 3 major
* MINOR 4 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Either remove or fill this block of code.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L118) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00108)
* MAJOR [Define and throw a dedicated exception instead of using a generic one.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L24) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00112)
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L118) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)
* MINOR [Define a constant instead of duplicating this literal "other" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L37) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "quote" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L65) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "scrollbox" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L86) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "navbox" 3 times.](https://github.com/Wikia/pandora/blob/5ee2d1e7879a309f0841dc0829707b1b8580f766/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L51) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)

**Pull request merged**
