### PR TITLE
Lower case standard responses

### PR DESCRIPTION
**Pull request by sqreek**
lets do this correctly :)
ping @Wikia/services-team

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 16 issues:
* MAJOR 6 major
* MINOR 8 minor
* INFO 2 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Method has 11 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L142) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* MINOR [Define a constant instead of duplicating this literal "Invalid response group" 3 times.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L116) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "No forum found for site id: %s with forum id: %s" 4 times.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L211) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Method has 8 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L224) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* MAJOR [Method has 11 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L118) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L287) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L96) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* MINOR [Define a constant instead of duplicating this literal "/1/forums" 4 times.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L201) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Reduce this lambda expression number of lines from 35 to at most 20.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L143) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MINOR [Define a constant instead of duplicating this literal "/%s/forums/%s?sortKey=%s&sortDirection=%s" 3 times.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L380) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Move this trailing comment on the previous empty line.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L151) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3ATrailingCommentCheck)
* MAJOR [6 duplicated blocks of code must be removed.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=common-java%3ADuplicatedBlocks)
* MINOR [Define a constant instead of duplicating this literal "Forum /w Threads" 4 times.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L313) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Reduce this lambda expression number of lines from 25 to at most 20.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ThreadResourceTest.java#L191) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MINOR [Immediately return this expression instead of assigning it to the temporary variable "post".](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/discussion/src/test/java/com/wikia/discussionservice/resources/ThreadResourceTest.java#L145) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1488)
* MINOR [Move this constructor to comply with Java Code Conventions.](https://github.com/Wikia/pandora/blob/f02361a7caefc7a303d5b69c8dd74c898b9ca075/service/user-attribute/src/main/java/com/wikia/services/userattribute/resources/AttributeResource.java#L48) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1213)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 16 issues:
* MAJOR 6 major
* MINOR 8 minor
* INFO 2 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Method has 8 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L224) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* MINOR [Define a constant instead of duplicating this literal "Invalid response group" 3 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L116) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "No forum found for site id: %s with forum id: %s" 4 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L211) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Method has 11 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L142) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* MAJOR [Method has 11 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L118) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L96) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L287) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* MINOR [Define a constant instead of duplicating this literal "/1/forums" 4 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L201) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "Forum /w Threads" 4 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L313) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Reduce this lambda expression number of lines from 35 to at most 20.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L143) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MINOR [Move this trailing comment on the previous empty line.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L151) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3ATrailingCommentCheck)
* MAJOR [6 duplicated blocks of code must be removed.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=common-java%3ADuplicatedBlocks)
* MINOR [Define a constant instead of duplicating this literal "/%s/forums/%s?sortKey=%s&sortDirection=%s" 3 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L380) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Immediately return this expression instead of assigning it to the temporary variable "post".](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ThreadResourceTest.java#L145) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1488)
* MAJOR [Reduce this lambda expression number of lines from 25 to at most 20.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ThreadResourceTest.java#L191) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MINOR [Move this constructor to comply with Java Code Conventions.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/user-attribute/src/main/java/com/wikia/services/userattribute/resources/AttributeResource.java#L48) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1213)

**Comment by nmonterroso** [comment]
Awesome! This bothered me every time I saw these warnings. Thanks for fixing LGTM!

**Comment by sqreek** [comment]
ping @jogura @idradm @lukaszkonieczny @kvas-damian 
If someone has open PR or work in progres please take a look if merge with master test work good for your projects

**Comment by WikiaTech** [comment]
SonarQube analysis reported 16 issues:
* MAJOR 6 major
* MINOR 8 minor
* INFO 2 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Define a constant instead of duplicating this literal "No forum found for site id: %s with forum id: %s" 4 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L211) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "Invalid response group" 3 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L116) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Method has 11 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L142) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* MAJOR [Method has 8 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ForumResource.java#L224) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L96) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* MAJOR [Method has 11 parameters, which is greater than 7 authorized.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L118) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* INFO [Complete the task associated to this TODO comment.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/main/java/com/wikia/discussionservice/resources/ThreadResource.java#L287) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1135)
* MAJOR [6 duplicated blocks of code must be removed.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=common-java%3ADuplicatedBlocks)
* MINOR [Define a constant instead of duplicating this literal "Forum /w Threads" 4 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L313) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Define a constant instead of duplicating this literal "/1/forums" 4 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L201) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MINOR [Move this trailing comment on the previous empty line.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L151) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3ATrailingCommentCheck)
* MAJOR [Reduce this lambda expression number of lines from 35 to at most 20.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L143) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MINOR [Define a constant instead of duplicating this literal "/%s/forums/%s?sortKey=%s&sortDirection=%s" 3 times.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ForumResourceTest.java#L380) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)
* MAJOR [Reduce this lambda expression number of lines from 25 to at most 20.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ThreadResourceTest.java#L191) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MINOR [Immediately return this expression instead of assigning it to the temporary variable "post".](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/discussion/src/test/java/com/wikia/discussionservice/resources/ThreadResourceTest.java#L145) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1488)
* MINOR [Move this constructor to comply with Java Code Conventions.](https://github.com/Wikia/pandora/blob/e585f456e0ff926b3e0fc63118c1b264e04a1273/service/user-attribute/src/main/java/com/wikia/services/userattribute/resources/AttributeResource.java#L48) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1213)

**Comment by drsnyder** [comment]
:+1: that was my fault

**Pull request merged**
