### PR TITLE
Dat 3413

### PR DESCRIPTION
**Pull request by rybmat**
https://wikia-inc.atlassian.net/browse/DAT-3413

matcher for clear templates

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/pandora/blob/f4dce72d4c5b4bfcc223399efed40f13b5f38c88/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L190) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)

**Comment by sqreek** [comment]
ping @rybmat

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/pandora/blob/f4dce72d4c5b4bfcc223399efed40f13b5f38c88/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L190) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)

**Comment by sqreek** [comment]
ping @rybmat 
We will close this PR if there is no active here

**Comment by SebastianMarzjan** [comment]
@sqreek We're discussing the approach, please leave it for some more time :)

**Comment by dianafa** [comment]
Should we close this PR? The ticket it relates to is closed as "Won't do" https://wikia-inc.atlassian.net/browse/DAT-3413

**Comment by SebastianMarzjan** [comment]
Yes, I think so.

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Either log or rethrow this exception.](https://github.com/Wikia/pandora/blob/f4dce72d4c5b4bfcc223399efed40f13b5f38c88/workers/template-classification-worker/src/test/java/com/wikia/workers/templateclassificationworker/TemplateParserTest.java#L190) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1166)

**Pull request closed without merging**
