### PR TITLE
fix tests in example

### PR DESCRIPTION
**Pull request by sqreek**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues:
* MAJOR 2 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Define and throw a dedicated exception instead of using a generic one.](https://github.com/Wikia/pandora/blob/403149c4f89fcb417a29e70d13a5c5ff2df0d2a7/service/example/src/main/java/com/wikia/exampleservice/guicemodule/ExampleModuleFactory.java#L31) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00112)
* MAJOR [Add a private constructor to hide the implicit public one.](https://github.com/Wikia/pandora/blob/403149c4f89fcb417a29e70d13a5c5ff2df0d2a7/service/example/src/main/java/com/wikia/exampleservice/guicemodule/ExampleModuleFactory.java#L9) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1118)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Move this trailing comment on the previous empty line.](https://github.com/Wikia/pandora/blob/02050d4190d67aa57e4add475ad7eec944fa69cf/service/example/src/main/java/com/wikia/exampleservice/ExampleServiceApplication.java#L23) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3ATrailingCommentCheck)

**Comment by pchojnacki** [comment]
LeGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Move this trailing comment on the previous empty line.](https://github.com/Wikia/pandora/blob/02050d4190d67aa57e4add475ad7eec944fa69cf/service/example/src/main/java/com/wikia/exampleservice/ExampleServiceApplication.java#L23) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3ATrailingCommentCheck)

**Pull request merged**
