### PR TITLE
add empty gradle properties for not block other developers

### PR DESCRIPTION
**Pull request by sqreek**
when new database credential was added into repo, it required to add new entries into gradle.properties.
Added empty ones will stop blocking other developers that don't know about it.

ping @Wikia/services-team

### CODE REVIEW

**Comment by pchojnacki** [comment]
does it work ?

**Comment by pchojnacki** [comment]
I mean are you able to override these values ? If so LGTM

**Comment by sqreek** [comment]
https://docs.gradle.org/current/userguide/build_environment.html

tested and works

btw. ping @idradm

**Comment by nmonterroso** [comment]
I hope people don't fill in appropriate values and commit/push them upstream. Can you add a comment to each of the gradle files to indicate that? We're creating more tribal knowledge here, where people have to know "yes these gradle.properties exist but I shouldn't fill them in"

**Pull request merged**
