### PR TITLE
Remove not in used notifications service

### PR DESCRIPTION
**Pull request by sqreek**
Remove unused code 

ping @Wikia/services-team @kvas-damian 

any objectives?

### CODE REVIEW

**Comment by nmonterroso** [comment]
LGTM. was super confusing to have `notification` and `notifications` service (are we sure we're removing the correct one?)

**Comment by sqreek** [comment]
I hope :wink:

**Comment by kvas-damian** [comment]
LGTM

**Comment by ArturKlajnerok** [comment]
Let's also cleanup some other stuff, LGTM :+1:

**Pull request merged**
