### PR TITLE
change invalid user id in user preference test

### PR DESCRIPTION
**Pull request by sqreek**
Becuse of sharing db, someone sometimes add some preferences for user with id 0.
It's allowed becuse there is no foreign key on user id in this table.
Change should prevent failing tests.

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [4 duplicated blocks of code must be removed.](https://github.com/Wikia/pandora/blob/8d518744766eb4961d58040e33f5e707ca66bb54/service/user-preference/src/test/java/com/wikia/userpreference/dao/WikiCitiesDAOIntegrationTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=common-java%3ADuplicatedBlocks)

**Comment by harnash** [comment]
Yeah. Thought about doing this similar way but really we need to rethink how tests are written. We shouldn't access dev-db. I can accept this workaround if we create separate ticket to clean up the tests in pandora (proper unit-test mocking, integration tests on clean db :/ and acceptance tests).

**Comment by nmonterroso** [comment]
looks like others had a similar idea :)

```
mysql> select * from user_properties where up_user <= 0;
+---------+------------------+----------+
| up_user | up_property      | up_value |
+---------+------------------+----------+
|      -5 | date             | 1        |
|      -5 | language         | en       |
|      -2 | date             | 1        |
|      -2 | language         | en       |
|      -1 | date             | 1        |
|      -1 | language         | en       |
|       0 | language         | en       |
|       0 | marketingallowed | 1        |
+---------+------------------+----------+
8 rows in set (0.00 sec)
```

**Comment by sqreek** [comment]
I will merge this temporary solution

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [4 duplicated blocks of code must be removed.](https://github.com/Wikia/pandora/blob/8d518744766eb4961d58040e33f5e707ca66bb54/service/user-preference/src/test/java/com/wikia/userpreference/dao/WikiCitiesDAOIntegrationTest.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=common-java%3ADuplicatedBlocks)

**Pull request merged**
